apiVersion: batch/v1
kind: Job
metadata:
    name: test1-job
spec:
    template:
        metadata:
             name: test1-job
        spec:
             restartPolicy: Never
             containers:
             - name: test1-job
               image: centos:7
               imagePullPolicy: IfNotPresent
               command:
               - "/bin/bash"
               - "-c"
               - "for i in 1 2 3 4 5; do echo $i; done"
