apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mysql-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: state-mysql
    serviceName: "mysql-service"
    template:
        metadata:
            labels:
                app: state-mysql
        spec:
            containers:
            - name: state-mysql
              image: mysql:5.7
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 3306
              env:
              - name: MYSQL_ROOT_PASSWORD
                value: "DD.08.dd"
              - name: MYSQL_DATABASE
                value: "wordpress"
              - name: MYSQL_USER
                value: "admin"
              - name: MYSQL_PASSWORD
                value: "DD.08.dd"
              volumeMounts:
                - name: mysql-data-volume
                  mountPath: /var/lib/mysql
            volumes:
                - name: mysql-data-volume
                  persistentVolumeClaim:
                      claimName: test-pvc-1g
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-service
spec:
        ports:
        - port: 3306
        selector:
                app: state-mysql
