apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-master-pv
    namespace: wordpress-namespace
spec:
    capacity:
        storage: 5G
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    nfs:
        server: 192.168.7.24
        path: /db5
