apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress-web
    namespace: wordpress-namespace
spec:
    replicas: 2
    selector:
       matchLabels:
           web-pv: wordpress
    template:
       metadata:
           labels:
              web-pv: wordpress
       spec:
           containers:
           - name: wordpress-web
             image: wordpress
             imagePullPolicy: IfNotPresent
             env:
              - name: WORDPRESS_DB_HOST
                value: "mysql-master-service"
              - name: WORDPRESS_DB_USER
                value: "admin"
              - name: WORDPRESS_DB_PASSWORD
                value: "DD.08.dd"
              - name: WORDPRESS_DB_NAME
                value: "wordpress"
              - name: WORDPRESS_TABLE_PREFIX
                value: "wp_"
             livenessProbe:
               httpGet:
                 path: /
                 port: 80
               initialDelaySeconds: 60
               timeoutSeconds: 10
               periodSeconds: 10
               failureThreshold: 3
             readinessProbe:
               tcpSocket:
                 port: 80
               initialDelaySeconds: 60
               timeoutSeconds: 10
               periodSeconds: 10
               failureThreshold: 3
             volumeMounts:
               - name: wordpress-pvc
                 mountPath: /var/www/html 
           volumes:
             - name: wordpress-pvc
               persistentVolumeClaim:
                   claimName: wordpress-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: wordpress-service
    namespace: wordpress-namespace
spec:
    ports:
    - port: 80
    selector:
        web-pv: wordpress
