apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-master-pvc
    namespace: wordpress-namespace
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 4Gi
