apiVersion: apps/v1
kind: Deployment
metadata:
    name: test1-deploy
spec:
    replicas: 6
    selector:
        matchLabels:
            app: dd1-nginx
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 2
            maxUnavailable: 1
    template:
        metadata:
            labels:
                app: dd1-nginx
        spec:
            containers:
            - name: nginx-dd1
              image: nginx:1.18
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 80
