apiVersion: apps/v1
kind: Deployment
metadata:
    name: test-deploy
spec:
    replicas: 4
    selector:
        matchLabels:
            app: dd1
    template:
        metadata:
            labels:
                app: dd1
        spec:
            containers:
            - name: centos7-dd1
              image: centos:7
              imagePullPolicy: IfNotPresent
              command:
              - sleep
              - "3600"
