apiVersion: v1
kind: Pod
metadata:
        name: test1
        namespace: wordpress  #pod属于哪个命名空间
spec:
        containers:
        - name: c1
          image: centos:7
          imagePullPolicy: IfNotPresent
          command:
          - sleep
          - "3600"
