apiVersion: v1
kind: Pod
metadata:
    name: mysql-5.7
    namespace: wordpress
spec:
    containers:
    - name: mysql-node1
      image: mysql:5.7
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: "DD.08.dd"
      - name: MYSQL_DATABASE
        value: "wordpress"
      resources:
        requests:
            cpu: "1"
            memory: "1G"
        limits:
            cpu: "2"
            memory: "2G"
