apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-data2
spec:
    capacity:
       storage: 10G
    accessModes:
       - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    nfs:
        server: 192.168.7.24
        path: /db2
