apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-data3
spec:
    capacity:
       storage: 5G
    accessModes:
       - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    nfs:
        server: 192.168.7.24
        path: /db3
