apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-data1
spec:
    capacity:
       storage: 2G
    accessModes:
       - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    nfs:
        server: 192.168.7.24
        path: /db1
