apiVersion: apps/v1
kind: Deployment
metadata:
    name: tomcat-service
spec:
    replicas: 3
    selector:
        matchLabels:
            app: service-tomcat
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 2
            maxUnavailable: 1
    template:
        metadata:
            labels:
                app: service-tomcat
        spec:
            containers:
            - name: tomcat-service-node1
              image: tomcat
              imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: tomcat-service
spec:
        type: NodePort
        ports:
        - port: 8080
          nodePort: 30001     #端口默认范围为 30000 - 32767
        selector:
                app: service-tomcat
